#+TITLE: MakeHaven Bicycle Framebuilding Setup

* Funding

Total cost: $2000

Fundraising goal: $1000 (MakeHaven matches)

* Location

The frame fixture will live in the welding area where the quenching tanks are currently located. The remaining tools can live in a bin or on a shelf.

* Framebuilding Process

Steps to build a bike frame:

[[file:framebuilding-steps.org]]

Cost for a MakeHaven member to build a frame:

[[file:member-cost-per-frame.org]]

* Tool Overview

Most of the below tools and their BOMs (bills of materials) can be found in [[./tools]].

** To Make

*** Frame Fixture =~$835=

[[file:tools/frame-fixture.org]]

Fixtures frame for brazing or welding.

*** Universal Disc Brake Fixture =$140=

[[file:tools/disc-brake-fixture.org]]

Positions disc brake caliper mounts using any popular standard (IS, post mount, flat mount) and their variations.

*** Dropout Gauges =$15=

[[file:tools/dropout-gauges.org]]

Quickly verifies correct dropout spacing.

*** Braze-on Clamps (4) =$25=

[[file:tools/braze-on-clamps.org]]

Secures braze-ons to tubes while they are silver-brazed.

*** Chainstay Mitering Fixture

Holds seatstays in the bridgeport for mitering at the BB and dropouts.

*** Seatstay Mitering Fixture

Holds seatstays in the bridgeport for mitering at the seat tube and dropouts.

*** Fork Welding Fixture

Fixtures fork at the correct length and offset for brazing or welding.

*** Bridge Mitering Fixture

Holds curved tubing for seatstay/chainstay bridges and allows them to be mitered symmetrically in the bridgeport.

*** Small-tube Mitering Fixture =$15=

[[file:tools/small-tube-mitering-fixture.org]]

Fixtures small, possibly-tapered tubes for mitering.

*** Head Tube Reamer/Facer

Reams/face head tube. The actual cutters will be purchased (priced separately), see below.

*** Aluminum Tube Blocks =$46=

[[file:tools/tube-blocks.org]]

Holds a specific diameter of tubing at the correct orientation in the bridgeport for mitering, or on the surface plate.

*** Plastic Tube Phase Blocks =$5=

3d-print extra tube blocks to keep tubes "in-phase" until they are welded. Similar to tube blocks, but only used to hold in the correct orientation relative to a reference plane.

*** Wood Tube Blocks for Bench Vise =$0=

[[file:tools/wood-tube-blocks.org]]

Hold tubes in the bench vise for mitering with hand files.

*** Hole Saw Arbors =$20=

[[file:tools/hole-saw-arbors.org]]

Rigidly connect hole saws to Bridgeport mill using 3/4" R8 collet.

*** Dummy Axles =$112=

[[file:tools/dummy-axles.org]]

Space and index the dropouts throughout the framebuilding process, and provide a connection point to various fixtures.

Variety of sizes for popular dropout/hub standards.

*** Tube Dimpler =$65=

[[file:tools/tube-dimpler.org]]

Form dimples in chainstays to increase tire, chainring, or crank arm clearance.

*** Simple Fork Blade Bender

CNC wood dies and a welded steel handle, delrin v-groove wheel

*** Wheel Tool

Uses/attachments:
- Canti boss holder
- Canti cable stop holder
- Road caliper brake bridge holder
- Fender boss bridge holder
- Plain-tube bridge holder
- Tire clearance checker
- Rear rack boss holder
- Stay holder plate?

*** Canti Post Mitering Fixture =$10=

[[file:tools/canti-post-mitering-fixture.org]]

Hold canti posts for mitering. Allow the correct miter angle to be set relative to its spring holes.

*** Bench Vise BB Pucks =$5=

Hold entire frame in bench vise for finishing work.

Get some old BSA fixed bb cups from BSBC and turn down the threads.

*** Dummy Headsets =$8=

[[file:tools/dummy-headsets.org]]

Secure fork to frame for transport, storage, or rack building.

** To Purchase

*** BikeCAD Pro Lifetime License (three machines) =$402=

Industry-standard software for designing bike frames.

https://www.bikecad.ca/bikecadpro

*** Dynafile (Handheld Pneumatic Belt Sander), used =$300=

With 11219 contact arm ($50 new).

Allows bronze fillets to be finished significantly faster than by hand, also a good general-purpose metal finishing tool (welds, etc).

*** Head Tube Reamer/Facer Cutters

Sizes:
- 43.95mm reamer (#788), $85
- 57mm facer (#690-XL), $106

(Devil's Gear has 34mm reamer)

*** Hole saws =$90=

Sizes:
- 5/8" (vent holes and paragon flat mount bosses) =$8=
- 3/4" (chainstays) =$8=
- 1" (round dropouts) =$9=
- 1-1/8" (seat tube) =$10=
- 1-1/4" (l seat tube) =$10=
- 1-3/8" (xl seat tube) =$11=
- 1-27/64" / 36mm Ruko (36mm ht) =$11=
  - (1-7/16" (36.5mm) is probably ok instead)
- 1-1/2" (bsa bb) =$11=
- 1-13/16" (46mm ht) =$11=

*** 1/8" Slitting Saw and Arbor =$40=

For:
- Slotting seatstays for traditional tabbed/plate dropouts
- Seatpost clamp slot
- Making aluminum tube blocks

Shars R8 arbor ($27), and cheap HSS slitting saws

*** Round files

Already have flat files, but few round/half-round files.

TODO sizes

** Already Have

- Bridgeport mills
- Horizontal bandsaw
- Oxy-acetylene brazing setup
- Surface plate

* TODO TODO

(search repo for scattered TODOs as well)

- frame fixture
  - model v4
  - BOM
  - update caliper requirement
    - use 300mm calipers with stops (HTX: 2, HTY: 1, DAY: 1)
- chainstay mitering fixture
  - Consider replacing extrusion with aluminum spine
  - .75" vise plate
  - tire profile mount
  - thinner arrow?
  - more metric
  - BOM
- seatstay mitering fixture
  - model
  - BOM
- (5) main tube mitering fixture
- (6) bridge mitering fixture
  - ... and bridge drilling fixture
- (7) EASY ht reamer/facer handles
  - model
  - BOM
- (9) EASY butt checker
- (10) EASY wheel tool
- (11) EASY bent-tube bb miter tool
- (12) EASY digital angle finder v block
- (13) EASY fork jig
- alignment tools (ht cone skewer, bb post, frame alignment gauge, etc)
  - dummy axle center scribe line for alignment?
- rotary draw tube bender(s) (ST and stays)
  - compatible with fork blades?
- fork raker
  - if main bender is incompatible
- more adjustable reamers (up to 31.6)?

** Not right now

- Time savers
  - Main tube mitering fixture setup with interlocking v-block, rotating phaser, and on-center rotary table
  - Water bottle boss drilling jig
    - Konga: "It’s not really that necessary. It will save some time when you don’t have to measure everything every time and it will help you when adding bottle bosses afterwards but you can really do the job with center drill and drill too."
  - Specialized braze-on fixtures
    - Make when needed, they're cheap
  - Seat tube mitering/slotting fixture(s), uses:
    - Bent ST-BB miter fixture
      - For now, use tube block after bend (must be more than (1.5"/2+2.25")=3" of straight tube under the bend, unless a special narrow tube block is used)
    - Internal dropper port slot
      - For now, use tube block / main tube mitering fixture / angle vise if needed
    - Seatpost clamp slot
      - For now, either do it before welding (end mill or slitting saw), or hold the entire frame vertically and use an end mill like handerhan (move bridgeport ram far back to clear seatstays), and either drill the relief hole before welding, or use a ball end mill that's the same width as the primary end mill at the end, or use a small round file.
- Low use
  - Stem fixture
  - Lug vise
  - Fork/wishbone mitering fixture (probably for lathe)
  - Thru-axle h-tool
    - Probably unnecessary with syntace dropouts. If not, simple enough to make when needed.
  - FD (front derailleur) tab fixture
    - Builds should use an FD adaptor clamp instead
  - Tube ovalizing dies
- Welding stuff (no TIG welder yet)
  - Heatsinks / purges (HT, ST, BB, round dropout)
  - Framebuilding-specific TIG torch upgrades
    - (for AlphaTIG) https://www.youtube.com/watch?v=V5AZvT6Gd88
  - High-temperature tape to cover purge holes (like mark at chumba) (Kapton tape?)
  - Clip-on BB purge hole shield
- Other
  - Gasflux Model 69 gasfluxer ($$)
  - Abrasive mitering setup ($$)
  - Hole saw actual cutting diameter gauge (my idea) (can use lathe for now)
  - Head tube badge arbor press die (simple enough to 3d-print on the spot)
  - Seat tube collar rotary welding fixture (silver braze them in for now)
  - DT-ST counter-miter finder
    - Probably unnecessary if doing the full main tube mitering fixture with rotating phase block
    - The dummy BB holder could be compatible with a future main tube mitering fixture and/or bottle boss drilling fixture -- make sure there's adequate clearance for a large HT [main tube] phase block
