#+TITLE: MakeHaven Bicycle Framebuilding Setup

* Funding

Total cost: $2000

Fundraising goal: $1000 (MakeHaven matches)

* Location

The frame jig will live in the welding area where the quenching tanks are currently located. The remaining tools can live in a bin or on a shelf.

* Framebuilding Process

Steps to build a bike frame:

[[file:framebuilding-steps.org]]

Cost for a MakeHaven member to build a frame:

[[file:member-cost-per-frame.org]]

* Tool Overview

Most of the below tools and their BOMs (bills of materials) can be found in [[./tools]].

** To Make

*** Frame Fixture =~$835=

[[file:tools/frame-fixture.org]]

Fixtures frame for brazing or welding.

*** Universal Disc Brake Fixture =$42=

[[file:tools/disc-brake-fixture.org]]

Positions disc brake caliper mounts using any popular standard (IS, post mount, flat mount) and their variations.

*** Dropout Gauges =$15=

[[file:tools/dropout-gauges.org]]

Quickly verifies correct dropout spacing.

*** Braze-on Clamps (4) =$25=

[[file:tools/braze-on-clamps.org]]

Secures braze-ons to tubes while they are silver-brazed.

*** Chainstay Mitering Fixture

Holds seatstays in the bridgeport for mitering at the BB and dropouts.

*** Seatstay Mitering Fixture

Holds seatstays in the bridgeport for mitering at the seat tube and dropouts.

*** Fork Fixture

Fixtures fork at the correct length and offset for brazing or welding.

*** Bridge Mitering Fixture

Holds curved tubing for seatstay/chainstay bridges and allows them to be mitered symmetrically in the bridgeport.

*** Small-tube Mitering Fixture =$15=

[[file:tools/small-tube-mitering-fixture.org]]

Fixtures small, possibly-tapered tubes for mitering.

*** Head Tube Reamer/Facer

Reams/face head tube. The actual cutters will be purchased (priced separately), see below.

*** Tube Blocks =$46=

[[file:tools/tube-blocks.org]]

Holds a specific diameter of tubing at the correct orientation in the bridgeport for mitering, or on the surface plate.

*** Tube Phase Blocks =$5=

3d-print extra tube blocks to keep tubes "in-phase" until they are welded. Similar to tube blocks, but only used to hold in the correct orientation relative to a reference plane.

*** Hole Saw Arbors =$20=

[[file:tools/hole-saw-arbors.org]]

Rigidly connect hole saws to Bridgeport mill using 3/4" R8 collet.

*** Dummy Axles =$112=

[[file:tools/dummy-axles.org]]

Space and index the dropouts throughout the framebuilding process, and provide a connection point to various fixtures.

Variety of sizes for popular dropout/hub standards.

*** Dimpler

Puts longitudinal dimples in chainstays to increase tire and/or chainring clearance, aided by a vise or the arbor press.

*** Simple Tube Bender

CNC wood dies and a welded steel handle, delrin v-groove wheel

*** Bent Seat Tube Mitering/Slotting Fixture

For:
- ST-BB miter
- Internal dropper port slot (w/ end mill)
- Seatpost clamp slot (w/ slitting saw) (holding entire frame, if compatible)

*** Wheel Tool

Uses/attachments:
- Canti boss holder
- Road caliper brake bridge holder
- Fender boss bridge holder
- Plain-tube bridge holder
- Tire clearance checker
- Rear rack boss holder
- Stay holder plate?

** To Purchase

*** BikeCAD Pro Lifetime License (three machines) =$402=

Industry-standard software for designing bike frames.

https://www.bikecad.ca/bikecadpro

*** Dynafile (Handheld Pneumatic Belt Sander), used =$300=

With 11219 contact arm ($50 new).

Allows bronze fillets to be finished significantly faster than by hand, also a good general-purpose metal finishing tool (welds, etc).

*** Head Tube Reamer/Facer Cutters

Sizes:
- 43.95mm reamer (#788), $85
- 57mm facer (#690-XL), $106

(Devil's Gear has 34mm reamer)

*** Hole saws =$90=

Sizes:
- 5/8" (vent holes and paragon flat mount bosses) =$8=
- 3/4" (chainstays) =$8=
- 1" (round dropouts) =$9=
- 1-1/8" (seat tube) =$10=
- 1-1/4" (l seat tube) =$10=
- 1-3/8" (xl seat tube) =$11=
- 1-27/64" / 36mm Ruko (36mm ht) =$11=
  - (1-7/16" (36.5mm) is probably ok instead)
- 1-1/2" (bsa bb) =$11=
- 1-13/16" (46mm ht) =$11=

*** 1/8" Slitting Saw and Arbor =$40=

For:
- Slotting seatstays for traditional tabbed/plate dropouts
- Seatpost clamp slot
- Making aluminum tube blocks

Shars R8 arbor ($27), and cheap HSS slitting saws

*** Round files

Already have flat files, but few round/half-round files.

** Already Have

- Bridgeport mills
- Horizontal bandsaw
- Oxy-acetylene brazing setup
- Surface plate

* TODO TODO

(search repo for scattered TODOs as well)

- frame fixture
  - model v4
  - BOM
- chainstay mitering fixture
  - Consider replacing extrusion with aluminum spine
  - .75" vise plate
  - tire profile mount
  - thinner arrow?
  - more metric
  - BOM
- seatstay mitering fixture
  - model
  - BOM
- bridge mitering fixture
  - model
  - BOM
- disc brake fixture
  - add flat mount 160, 180
  - make easier to fixture/machine
    - consider bolt-on inserts for different diameters/offsets (like lichen)
  - more metric
  - Final BOM
- ht reamer/facer handles
  - model
  - BOM
- dimpler
  - model
  - BOM
- fork raker
- tube bender
- wheel tool
- fd fixture
- butt checker
- simple main tube mitering fixture
- dt-st "bird's notch" miter locator
- bent st mitering/slotting fixture
- cal-x-tender or giant calipers for frame fixture setup and tube length measurements
- soft bb pucks for vise (or just old fixed cups with threads removed)
- soft ht-steerer pucks for transport
- alignment tools
- canti post mitering fixture (double like cobra)?
- wood tube blocks for vise / hand-file mitering
- fork jig
- thru-axle h-tool

** Not right now

- Time savers
  - Main tube mitering fixture setup with interlocking v-block, phasing block, and on-center rotary table
  - Water bottle boss drilling jig
    - Konga: "It’s not really that necessary. It will save some time when you don’t have to measure everything every time and it will help you when adding bottle bosses afterwards but you can really do the job with center drill and drill too."
- Low use
  - Stem fixture
  - Lug vise
  - Fork/wishbone mitering fixture
- TIG
  - TIG heat sinks / purges
  - high temperature tape to cover purge holes (like mark at chumba) (Kapton tape?)
- Other
  - Gasflux Model 69 gasfluxer ($$)
  - Hole saw actual cutting diameter gauge (my idea)
  - Head tube badge arbor press die
  - Seat collar welding fixture
  - DT shifter boss fixture
  - Abrasive mitering setup
