#+TITLE: MakeHaven Bicycle Framebuilding Setup

* Funding

Total cost: $2000

Fundraising goal: $1000 (MakeHaven matches)

* Location

The frame jig will live in the welding area where the quenching tanks are currently located. The remaining tools can live in a bin or on a shelf.

* Framebuilding Process

Steps to build a bike frame:

[[file:framebuilding-steps.org]]

Cost for a MakeHaven member to build a frame:

[[file:member-cost-per-frame.org]]

* Tool Overview

Most of the below tools and their BOMs (bills of materials) can be found in [[./tools]].

** To Make

*** Frame Fixture =~$680=

[[file:tools/frame-fixture.org]]

Fixtures frame for brazing or welding.

*** Universal Disc Brake Fixture =$42=

[[file:tools/disc-brake-fixture.org]]

Positions disc brake caliper mounts using any popular standard (IS, post mount, flat mount) and their variations.

*** Dropout Gauges =$15=

[[file:tools/dropout-gauges.org]]

Quickly verifies correct dropout spacing.

*** Braze-on Clamps (4) =$25=

[[file:tools/braze-on-clamps.org]]

Secures braze-ons to tubes while they are silver-brazed.

*** Chainstay Mitering Fixture

Holds seatstays in the bridgeport for mitering at the BB and dropouts.

*** Seatstay Mitering Fixture

Holds seatstays in the bridgeport for mitering at the seat tube and dropouts.

*** Fork Fixture

Fixtures fork at the correct length and offset for brazing or welding.

*** Bridge Mitering Fixture

Holds curved tubing for seatstay/chainstay bridges and allows them to be mitered symmetrically in the bridgeport.

*** Small-tube Mitering Fixture =$15=

[[file:tools/small-tube-mitering-fixture.org]]

Fixtures small, possibly-tapered tubes for mitering.

*** Head Tube Reamer/Facer

Reams/face head tube. The actual cutters will be purchased (priced separately), see below.

*** Tube Blocks =$75=

[[file:tools/tube-blocks.org]]

Holds a specific diameter of tubing at the correct orientation in the bridgeport for mitering, or on the surface plate.

*** Tube Phase Blocks =$5=

3d-print extra tube blocks to keep tubes "in-phase" until they are welded. Similar to tube blocks, but only used to hold in the correct orientation relative to a reference plane.

*** Hole Saw Arbors

Rigidly connect hole saws to Bridgeport mill using 3/4" R8 collet.

Sizes:
- 2x 1/2" 2-1/2"
- 2x 5/8" 2-1/2"
- 1x 1/2" 7-1/4"

Dimensions:
- 3/4" OD shank
- Smaller 1/2"-20 thread for <=1-1/8" hole saws
- Larger 5/8"-18 thread for >=1-1/4" hole saws, with reinforcement
- Use longer length arbor for one-setup round dropout mitering with stay mitering fixtures

*** Dummy Axles =$132=

[[file:tools/dummy-axles.org]]

Space and index the dropouts throughout the framebuilding process, and provide a connection point to various fixtures.

Variety of sizes for popular dropout/hub standards.

*** Dimpler

Puts longitudinal dimples in chainstays to increase tire and/or chainring clearance, aided by a vise or the arbor press.

*** Simple Tube Bender

CNC wood dies and a welded steel handle, delrin v-groove wheel

*** Bent Seat Tube Mitering Fixture

** To Purchase

*** BikeCAD Pro Lifetime License (three machines) =$402=

Industry-standard software for designing bike frames.

https://www.bikecad.ca/bikecadpro

*** Dynafile (Handheld Pneumatic Belt Sander), used =$300=

With 11219 contact arm ($50 new).

Allows bronze fillets to be finished significantly faster than by hand, also a good general-purpose metal finishing tool (welds, etc).

*** Head Tube Reamer/Facer Cutters

Sizes:
- 43.95mm reamer (#788), $85
- 57mm facer (#690-XL), $106

(Devil's Gear has 34mm reamer)

*** Hole saws =$90=

Sizes:
- 5/8" (vent holes) =$8=
- 3/4" (chainstays) =$8=
- 1" (round dropouts) =$9=
- 1-1/8" (seat tube) =$10=
- 1-1/4" (l seat tube) =$10=
- 1-3/8" (xl seat tube) =$11=
- 1-27/64" / 36mm Ruko (36mm ht) =$11=
- 1-1/2" (bsa bb) =$11=
- 1-13/16" (46mm ht) =$11=

*** 1/8" Slitting Saw and Arbor =$40=

For:
- Slotting seatstays for traditional tabbed/plate dropouts
- Seatpost clamp slot
- Making aluminum tube blocks

Shars R8 arbor ($27), and cheap HSS slitting saws

** Already Have

- Bridgeport mills
- Horizontal bandsaw
- Oxy-acetylene brazing setup
- Hand files
- Surface plate

* TODO TODO

(search repo for scattered TODOs as well)

- frame fixture
  - model v2
  - BOM
- chainstay mitering fixture
  - 50mm extrusion
  - .75" vise plate
  - tire profile mount
  - thinner arrow?
  - metricification
  - BOM
- seatstay mitering fixture
  - model
  - BOM
- bridge mitering fixture
  - model
  - BOM
- disc brake fixture
  - add flat mount 160, 180
  - make easier to fixture/machine
  - consider bolt-on inserts for different diameters/offsets (like lichen)
  - metrification
  - Final BOM
- tube blocks
  - BOM
- ht reamer/facer
  - model
  - BOM
- hole saw arbors
  - model
  - BOM
- dimpler
  - model
  - BOM
- simple tube bender
  - model
  - BOM
- bent st mitering fixture?
  - model
  - BOM
- stem fixture?
- main tube holder mitering?
- head tube badge die?
